### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by cyromaniac** [thealanle/bio-pipelines#15]
hey bro, sorry to bug you. i know you probably get bugged everyone once in a while about this, but i was wondering if you would be willing to sell your minecraft account? i own a pretty decently large server, and i've been looking around for an account to base my alias around. i would be willing to offer you a good amount of money. i know you're probably very weary of a scam, but i can assure you i'm very interested in this account. i would be willing to pay you first before you give me the account, just so you know i am being honest with you. again, sorry to bother you!

**Comment by thealanle** [comment]
Thanks, but I'm not interested. Cheers.

**Comment by cyromaniac** [comment]
Fair enough, please once you get a second migrate your account so it's not sitting dormant, since mojang was talking about possibly temporarily locking accounts.

**Comment by cyromaniac** [comment]
i know you're not interested at the moment, but in the future you may change your mind, my offer would be $1,000, please just hit me up if you ever change your mind.

cyromcnetwork@gmail.com
